# Demo data for local development: 5 promotional campaigns and 50 coupons that
# cover every state the checkout has to handle — active, used, disabled, expired
# (campaign past its end date) and awaiting approval.
#
# Idempotent and deterministic: running it again converges to the same data
# instead of duplicating it (bin/rails db:seed, or automatically on db:prepare).
# Coupon codes come from CouponGenerationService, so they are random by design.
#
# db:prepare seeds every database it creates, in any environment (including a
# production deploy and the test DB), so skip instead of aborting outside dev.
unless Rails.env.development?
  puts "db/seeds.rb: demo data is only loaded in development; skipping #{Rails.env}."
  return
end

Faker::Config.locale = "pt-BR"
Faker::Config.random = Random.new(2026)

password = "senha123"
today = Date.current

# Next occurrence (today or later) of a yearly date.
upcoming = ->(month, day) { Date.new(today.year, month, day).then { |d| d < today ? d.next_year : d } }
# Black Friday: fourth Friday of November.
black_friday = lambda do |year|
  first_of_november = Date.new(year, 11, 1)
  first_of_november + ((5 - first_of_november.wday) % 7) + 21
end
next_black_friday = black_friday.(today.year).then { |d| d < today ? black_friday.(today.year + 1) : d }
last_consumer_day = Date.new(today.year, 3, 15).then { |d| d >= today ? d.prev_year : d }

hooks = [
  "frete grátis para todo o Brasil", "parcele em até 10x sem juros", "estoque limitado",
  "válido para o app e o site", "cumulativo com o cashback da loja", "só enquanto durar o estoque"
].freeze

category_names = {
  "ELETRO" => "Eletrônicos", "GAMES" => "Games", "MODA" => "Moda",
  "CASA" => "Casa e Decoração", "LIVROS" => "Livros", "BELEZA" => "Beleza"
}.freeze

campaigns = [
  { name: "Black Friday", code: "BLACKFRIDAY30", discount_rate: 30, expiration_date: next_black_friday + 2,
    categories: %w[ELETRO GAMES CASA], approved: true, used: 4, disabled: 1 },
  { name: "Cyber Monday", code: "CYBER25", discount_rate: 25, expiration_date: next_black_friday + 3,
    categories: %w[ELETRO GAMES], approved: true, used: 2, disabled: 0 },
  { name: "Natal Premiado", code: "NATAL15", discount_rate: 15, expiration_date: upcoming.(12, 24),
    categories: %w[MODA BELEZA LIVROS], approved: true, used: 0, disabled: 1 },
  { name: "Dia do Consumidor", code: "CONSUMIDOR20", discount_rate: 20, expiration_date: last_consumer_day,
    categories: %w[MODA CASA BELEZA], approved: true, used: 6, disabled: 0 },
  { name: "Volta às Aulas", code: "VOLTAAULAS", discount_rate: 12.5, expiration_date: upcoming.(2, 15),
    categories: %w[LIVROS ELETRO], approved: false, used: 0, disabled: 0 }
].freeze
coupons_per_campaign = 10

ActiveRecord::Base.transaction do
  # Fixed logins for trying the app; the marketing team is generated by Faker.
  approver = User.find_or_create_by!(email: "aprovador@promotion.dev") { |u| u.password = password }
  marketing_team = [User.find_or_create_by!(email: "gerente@promotion.dev") { |u| u.password = password }]
  marketing_team += Array.new(2) do
    # Faker's pt-BR emails keep accents/titles ("cec#lia.jr"), so build a clean one.
    email = "#{Faker::Name.first_name} #{Faker::Name.last_name}".parameterize(separator: ".") + "@promotion.dev"
    User.find_or_create_by!(email:) { |u| u.password = password }
  end

  categories = category_names.to_h do |code, name|
    [code, Category.find_or_create_by!(code:) { |c| c.name = name }]
  end

  campaigns.each_with_index do |campaign, index|
    promotion = Promotion.find_or_initialize_by(code: campaign[:code])
    promotion.assign_attributes(
      name: campaign[:name],
      description: "#{campaign[:name]}: #{campaign[:discount_rate].to_s.tr('.', ',')}% OFF em " \
                   "#{campaign[:categories].map { categories[it].name }.to_sentence} — " \
                   "#{Faker::Base.sample(hooks)}.",
      discount_rate: campaign[:discount_rate],
      coupon_quantity: coupons_per_campaign,
      expiration_date: campaign[:expiration_date],
      user: marketing_team[index % marketing_team.size],
      categories: categories.values_at(*campaign[:categories])
    )
    promotion.save!

    promotion.approve!(approver) if campaign[:approved] && !promotion.approved?
    CouponGenerationService.call(promotion:) # tops up only what's missing

    # Deterministic statuses: the first N coupons (by id) are used, the next M disabled.
    ids = promotion.coupons.order(:id).ids
    used_ids = ids.first(campaign[:used])
    disabled_ids = ids.drop(campaign[:used]).first(campaign[:disabled])
    promotion.coupons.update_all(status: Coupon.statuses[:able])
    Coupon.where(id: used_ids).update_all(status: Coupon.statuses[:used])
    Coupon.where(id: disabled_ids).update_all(status: Coupon.statuses[:disable])
  end
end

puts format("%-18s %-11s %-12s %5s %5s %5s %5s", "Campanha", "Expira em", "Situação", "Ativo", "Usado", "Desab", "Total")
Promotion.includes(:coupons, :promotion_approval).where(code: campaigns.pluck(:code)).order(:expiration_date).each do |p|
  situation = if p.expired? then "expirada" elsif p.approved? then "vigente" else "aguardando" end
  counts = p.coupons.map(&:status).tally
  puts format("%-18s %-11s %-12s %5d %5d %5d %5d", p.name, p.expiration_date.strftime("%d/%m/%Y"), situation,
              counts.fetch("able", 0), counts.fetch("used", 0), counts.fetch("disable", 0), p.coupons.size)
end
puts "\nLogin: gerente@promotion.dev / aprovador@promotion.dev — senha: #{password}"
